In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ATP.csv")

In [3]:
df

,best_of,draw_size,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_ace,l_bpFaced,l_bpSaved,l_df,...,winner_age,winner_entry,winner_hand,winner_ht,winner_id,winner_ioc,winner_name,winner_rank,winner_rank_points,winner_seed
0,5,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,R,NaN,110023,AUS,Richard Coulthard,NaN,NaN,NaN
1,5,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.520876,NaN,R,NaN,109803,AUS,John Brown,NaN,NaN,NaN
2,5,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.216290,NaN,R,NaN,100257,AUS,Ross Case,NaN,NaN,NaN
3,5,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.264203,NaN,R,NaN,100105,AUS,Allan Stone,NaN,NaN,5.0
4,5,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.861739,NaN,R,NaN,109966,AUS,Warren Jacques,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169685,3,NaN,54.0,43.0,16.0,15.0,13.0,5.0,3.0,1.0,...,22.740000,NaN,R,NaN,106426,CHI,Christian Garin,92.0,620.0,NaN
169686,3,NaN,23.0,12.0,5.0,7.0,0.0,8.0,3.0,2.0,...,20.180000,NaN,R,NaN,134770,NOR,Casper Ruud,108.0,527.0,NaN
169687,3,NaN,56.0,39.0,13.0,12.0,5.0,5.0,3.0,1.0,...,28.780000,NaN,L,185.0,105550,ARG,Guido Pella,48.0,975.0,3.0
169688,3,NaN,34.0,24.0,11.0,10.0,5.0,6.0,3.0,0.0,...,22.740000,NaN,R,NaN,106426,CHI,Christian Garin,92.0,620.0,NaN
169689,3,NaN,35.0,26.0,9.0,11.0,5.0,7.0,3.0,4.0,...,28.780000,NaN,L,185.0,105550,ARG,Guido Pella,48.0,975.0,3.0

In [4]:
df.columns

Index(['best_of', 'draw_size', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms',
       'l_ace', 'l_bpFaced', 'l_bpSaved', 'l_df', 'l_svpt', 'loser_age',
       'loser_entry', 'loser_hand', 'loser_ht', 'loser_id', 'loser_ioc',
       'loser_name', 'loser_rank', 'loser_rank_points', 'loser_seed',
       'match_num', 'minutes', 'round', 'score', 'surface', 'tourney_date',
       'tourney_id', 'tourney_level', 'tourney_name', 'w_1stIn', 'w_1stWon',
       'w_2ndWon', 'w_SvGms', 'w_ace', 'w_bpFaced', 'w_bpSaved', 'w_df',
       'w_svpt', 'winner_age', 'winner_entry', 'winner_hand', 'winner_ht',
       'winner_id', 'winner_ioc', 'winner_name', 'winner_rank',
       'winner_rank_points', 'winner_seed'],
      dtype='object')

In [5]:
short = df[["tourney_name", "surface", "tourney_level", "tourney_date", "winner_name" , "winner_ioc" , 'loser_name', "loser_ioc" , 'score']]

In [6]:
short

,tourney_name,surface,tourney_level,tourney_date,winner_name,winner_ioc,loser_name,loser_ioc,score
0,Australian Chps.,Grass,G,19680119,Richard Coulthard,AUS,Max Senior,AUS,12-10 7-5 4-6 7-5
1,Australian Chps.,Grass,G,19680119,John Brown,AUS,Ernie Mccabe,AUS,6-3 6-2 6-4
2,Australian Chps.,Grass,G,19680119,Ross Case,AUS,Gondo Widjojo,INA,6-4 3-6 6-3 7-5
3,Australian Chps.,Grass,G,19680119,Allan Stone,AUS,Robert Layton,AUS,6-4 6-2 6-1
4,Australian Chps.,Grass,G,19680119,Warren Jacques,AUS,Bert Kearney,AUS,6-4 6-1 7-5
...,...,...,...,...,...,...,...,...,...
169685,Sao Paulo,Clay,A,20190225,Christian Garin,CHI,Leonardo Mayer,ARG,4-6 6-4 6-4
169686,Sao Paulo,Clay,A,20190225,Casper Ruud,NOR,Hugo Dellien,BOL,6-1 6-1
169687,Sao Paulo,Clay,A,20190225,Guido Pella,ARG,Laslo Djere,SRB,7-6(10) 7-6(1)
169688,Sao Paulo,Clay,A,20190225,Christian Garin,CHI,Casper Ruud,NOR,6-4 6-4
169689,Sao Paulo,Clay,A,20190225,Guido Pella,ARG,Christian Garin,CHI,7-5 6-3

In [7]:
clay = short[short["surface"] == "Clay"]
clay

,tourney_name,surface,tourney_level,tourney_date,winner_name,winner_ioc,loser_name,loser_ioc,score
124,Cincinnati,Clay,M,19680707,Tom Mozur,USA,Joaquin Loyo Mayo,MEX,7-5 4-6 6-3
125,Cincinnati,Clay,M,19680707,William Harris,USA,Steve Faulk,USA,6-4 2-6 6-3
126,Cincinnati,Clay,M,19680707,Jaime Fillol,CHI,Dick Dell,USA,6-4 6-2
127,Cincinnati,Clay,M,19680707,Tom Gorman,USA,Brian Cheney,USA,9-7 6-8 6-4
128,Cincinnati,Clay,M,19680707,Allan Stone,AUS,Tom Mozur,USA,6-3 6-2
...,...,...,...,...,...,...,...,...,...
169685,Sao Paulo,Clay,A,20190225,Christian Garin,CHI,Leonardo Mayer,ARG,4-6 6-4 6-4
169686,Sao Paulo,Clay,A,20190225,Casper Ruud,NOR,Hugo Dellien,BOL,6-1 6-1
169687,Sao Paulo,Clay,A,20190225,Guido Pella,ARG,Laslo Djere,SRB,7-6(10) 7-6(1)
169688,Sao Paulo,Clay,A,20190225,Christian Garin,CHI,Casper Ruud,NOR,6-4 6-4
169689,Sao Paulo,Clay,A,20190225,Guido Pella,ARG,Christian Garin,CHI,7-5 6-3

In [8]:
clay["Year"] = pd.to_datetime(clay["tourney_date"], format='%Y%m%d').dt.year

C:\Users\Manu\AppData\Local\Temp/ipykernel_15692/267747142.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clay["Year"] = pd.to_datetime(clay["tourney_date"], format='%Y%m%d').dt.year

In [9]:
clay = clay[clay["Year"] < 2019]
clay

,tourney_name,surface,tourney_level,tourney_date,winner_name,winner_ioc,loser_name,loser_ioc,score,Year
124,Cincinnati,Clay,M,19680707,Tom Mozur,USA,Joaquin Loyo Mayo,MEX,7-5 4-6 6-3,1968
125,Cincinnati,Clay,M,19680707,William Harris,USA,Steve Faulk,USA,6-4 2-6 6-3,1968
126,Cincinnati,Clay,M,19680707,Jaime Fillol,CHI,Dick Dell,USA,6-4 6-2,1968
127,Cincinnati,Clay,M,19680707,Tom Gorman,USA,Brian Cheney,USA,9-7 6-8 6-4,1968
128,Cincinnati,Clay,M,19680707,Allan Stone,AUS,Tom Mozur,USA,6-3 6-2,1968
...,...,...,...,...,...,...,...,...,...,...
168588,Davis Cup G2 R3: URU vs MEX,Clay,D,20180915,Martin Cuevas,URU,Lucas Gomez,MEX,6-4 6-3,2018
168589,Davis Cup G2 R3: URU vs MEX,Clay,D,20180915,Pablo Cuevas,URU,Gerardo Lopez Villasenor,MEX,1-6 7-6(5) 6-3,2018
169036,Davis Cup WG F: FRA vs CRO,Clay,D,20181123,Borna Coric,CRO,Jeremy Chardy,FRA,6-2 7-5 6-4,2018
169037,Davis Cup WG F: FRA vs CRO,Clay,D,20181123,Marin Cilic,CRO,Jo Wilfried Tsonga,FRA,6-3 7-5 6-4,2018
169038,Davis Cup WG F: FRA vs CRO,Clay,D,20181123,Marin Cilic,CRO,Lucas Pouille,FRA,7-6(3) 6-3 6-3,2018

In [10]:
argClay = clay[clay["winner_ioc"] == "ARG"]
argClay

,tourney_name,surface,tourney_level,tourney_date,winner_name,winner_ioc,loser_name,loser_ioc,score,Year
137,Barcelona,Clay,A,19680607,Gustavo Guerrero,ARG,Fernando Gentil,BRA,W/O,1968
2124,Gstaad,Clay,A,19690727,Julian Ganzabal,ARG,Fred Stolle,AUS,4-6 6-3 6-1,1969
2589,Buenos Aires,Clay,A,19691111,Guillermo Vilas,ARG,Frew Mcmillan,RSA,7-5 6-1 6-2,1969
2599,Buenos Aires,Clay,A,19691111,Julian Ganzabal,ARG,Lito Alvarez,ARG,6-1 8-6 6-4,1969
2605,Buenos Aires,Clay,A,19691111,Guillermo Vilas,ARG,Patricio Cornejo,CHI,6-1 4-6 4-6 6-4 6-4,1969
...,...,...,...,...,...,...,...,...,...,...
168149,Hamburg,Clay,A,20180723,Leonardo Mayer,ARG,Diego Sebastian Schwartzman,ARG,6-3 4-6 6-3,2018
168153,Hamburg,Clay,A,20180723,Leonardo Mayer,ARG,Jozef Kovalik,SVK,6-7(6) 6-4 7-6(7),2018
168545,Davis Cup WG PO: ARG vs COL,Clay,D,20180914,Diego Sebastian Schwartzman,ARG,Santiago Giraldo,COL,6-3 6-1 6-7(3) 6-1,2018
168546,Davis Cup WG PO: ARG vs COL,Clay,D,20180914,Guido Pella,ARG,Daniel Elahi Galan Riveros,COL,3-6 6-4 4-6 6-3 6-2,2018
168547,Davis Cup WG PO: ARG vs COL,Clay,D,20180914,Horacio Zeballos,ARG,Nicolas Mejia,COL,7-5 6-2,2018

In [11]:
argClay["winner_name"].value_counts().head(20)

Guillermo Vilas           644
Jose Luis Clerc           304
Juan Monaco               236
Guillermo Perez Roldan    234
Martin Jaite              230
Gaston Gaudio             212
Juan Ignacio Chela        193
Horacio De La Pena        164
Franco Davin              152
Mariano Zabaleta          149
Jose Acasuso              141
David Nalbandian          138
Agustin Calleri           135
Ricardo Cano              135
Guillermo Coria           134
Franco Squillari          129
Guillermo Canas           121
Alberto Mancini           117
Mariano Puerta            108
Carlos Berlocq             99
Name: winner_name, dtype: int64

In [12]:
argClay["winner_name"].value_counts().head(20).sum()

3775

In [13]:
def auxFunc(year):
    if 1698<=year<=1983:
        return "Era Vilas"
    elif 1984<=year<=1999:
        return "84-99"
    elif 2000<=year<=2010:
        return "Era La Legion"
    else:
        return "Era Davis"

In [14]:
argClay["era"] = argClay["Year"].apply(lambda x: auxFunc(x))

C:\Users\Manu\AppData\Local\Temp/ipykernel_15692/1019797685.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  argClay["era"] = argClay["Year"].apply(lambda x: auxFunc(x))

In [15]:
argClay

,tourney_name,surface,tourney_level,tourney_date,winner_name,winner_ioc,loser_name,loser_ioc,score,Year,era
137,Barcelona,Clay,A,19680607,Gustavo Guerrero,ARG,Fernando Gentil,BRA,W/O,1968,Era Vilas
2124,Gstaad,Clay,A,19690727,Julian Ganzabal,ARG,Fred Stolle,AUS,4-6 6-3 6-1,1969,Era Vilas
2589,Buenos Aires,Clay,A,19691111,Guillermo Vilas,ARG,Frew Mcmillan,RSA,7-5 6-1 6-2,1969,Era Vilas
2599,Buenos Aires,Clay,A,19691111,Julian Ganzabal,ARG,Lito Alvarez,ARG,6-1 8-6 6-4,1969,Era Vilas
2605,Buenos Aires,Clay,A,19691111,Guillermo Vilas,ARG,Patricio Cornejo,CHI,6-1 4-6 4-6 6-4 6-4,1969,Era Vilas
...,...,...,...,...,...,...,...,...,...,...,...
168149,Hamburg,Clay,A,20180723,Leonardo Mayer,ARG,Diego Sebastian Schwartzman,ARG,6-3 4-6 6-3,2018,Era Davis
168153,Hamburg,Clay,A,20180723,Leonardo Mayer,ARG,Jozef Kovalik,SVK,6-7(6) 6-4 7-6(7),2018,Era Davis
168545,Davis Cup WG PO: ARG vs COL,Clay,D,20180914,Diego Sebastian Schwartzman,ARG,Santiago Giraldo,COL,6-3 6-1 6-7(3) 6-1,2018,Era Davis
168546,Davis Cup WG PO: ARG vs COL,Clay,D,20180914,Guido Pella,ARG,Daniel Elahi Galan Riveros,COL,3-6 6-4 4-6 6-3 6-2,2018,Era Davis
168547,Davis Cup WG PO: ARG vs COL,Clay,D,20180914,Horacio Zeballos,ARG,Nicolas Mejia,COL,7-5 6-2,2018,Era Davis

In [16]:
argClay["era"].value_counts()

84-99            1759
Era La Legion    1651
Era Vilas        1173
Era Davis         662
Name: era, dtype: int64

In [17]:
eraVilas = argClay["era"] == "Era Vilas"
vilas = argClay[eraVilas]
vilas["winner_name"].value_counts()

Guillermo Vilas           566
Jose Luis Clerc           269
Ricardo Cano              135
Julian Ganzabal            46
Lito Alvarez               35
Alejandro Ganzabal         25
Carlos Castellan           17
Roberto Arguello           13
Fernando Dalla Fontana     11
Gustavo Tiberti            10
Guillermo Aubone           10
Eduardo Bengoechea          5
Gustavo Guerrero            5
Raul Peralta                5
Martin Jaite                5
Alejandro Gattiker          3
Enrique Caviglia            2
Tito Vasquez                2
Roberto Aubone              2
Tomas Lynch                 2
Carlos Lando                1
Hugo Varela                 1
Carlos Gattiker             1
Jason Van Kerckhoven        1
Gabriel Auroux              1
Name: winner_name, dtype: int64

In [18]:
ochoCuatro = argClay["era"] == "84-99"
ochoCuatro = argClay[ochoCuatro]
ochoCuatro["winner_name"].value_counts()

Guillermo Perez Roldan    234
Martin Jaite              225
Horacio De La Pena        164
Franco Davin              152
Alberto Mancini           117
Eduardo Bengoechea         81
Hernan Gumy                81
Guillermo Vilas            78
Javier Frana               66
Christian Miniussi         53
Roberto Azar               48
Franco Squillari           48
Gabriel Markus             47
Roberto Arguello           45
Mariano Zabaleta           43
Jose Luis Clerc            35
Mariano Puerta             31
Marcelo Ingaramo           30
Francisco Yunis            27
Lucas Arnold Ker           19
Alejandro Ganzabal         19
Guillermo Canas            14
Daniel Orsanic             13
Martin Rodriguez           10
Gaston Etlis                9
Carlos Castellan            9
Gustavo Giussani            8
Gaston Gaudio               8
Guillermo Rivas             7
Marcelo Charpentier         5
Roberto Saad                4
Martin Stringari            4
Agustin Calleri             3
Gustavo Garetto             3
Luis Lobo                   2
Sebastian Prieto            2
Francisco Cabello           2
Gustavo Guerrero            2
Mariano Hood                2
Eduardo Medica              2
Agustin Garizzio            1
Juan Garat                  1
Andy Zingman                1
Gustavo Luza                1
Gustavo Tiberti             1
Thomas Stalhandske          1
Gerardo Mirad               1
Name: winner_name, dtype: int64

In [19]:
legion = argClay["era"] == "Era La Legion"
legion = argClay[legion]
legion["winner_name"].value_counts()

Gaston Gaudio               204
Juan Ignacio Chela          165
Jose Acasuso                139
Juan Monaco                 135
Guillermo Coria             134
Agustin Calleri             132
David Nalbandian            120
Guillermo Canas             107
Mariano Zabaleta            106
Franco Squillari             81
Mariano Puerta               77
Martin Vassallo Arguello     38
Juan Martin Del Potro        32
Eduardo Schwank              23
Sergio Roitman               20
Carlos Berlocq               18
Maximo Gonzalez              16
Diego Hartfield              15
Leonardo Mayer               11
Horacio Zeballos             10
Federico Browne               9
Hernan Gumy                   8
Brian Dabul                   7
Diego Junqueira               6
Edgardo Massa                 6
Juan Pablo Guzman             5
Gaston Etlis                  5
Juan Pablo Brzezicki          5
Martin Rodriguez              4
Sebastian Decoud              4
Diego Veronelli               2
Gustavo Marcaccio             2
Mariano Hood                  2
Ignacio Hirigoyen             1
Marcelo Charpentier           1
Sebastian Prieto              1
Name: winner_name, dtype: int64

In [20]:
davis = argClay["era"] == "Era Davis"
davis = argClay[davis]
davis["winner_name"].value_counts()

Juan Monaco                    101
Federico Delbonis               84
Carlos Berlocq                  81
Leonardo Mayer                  73
Diego Sebastian Schwartzman     55
Horacio Zeballos                48
Juan Martin Del Potro           46
Guido Pella                     37
Juan Ignacio Chela              28
David Nalbandian                18
Renzo Olivo                     18
Nicolas Kicker                  15
Facundo Bagnis                  15
Marco Trungelliti                9
Maximo Gonzalez                  9
Martin Alund                     7
Eduardo Schwank                  7
Guido Andreozzi                  3
Diego Junqueira                  3
Jose Acasuso                     2
Facundo Arguello                 1
Juan Pablo Brzezicki             1
Federico Coria                   1
Name: winner_name, dtype: int64

In [21]:
vilas["winner_name"].value_counts()[3:]

Julian Ganzabal           46
Lito Alvarez              35
Alejandro Ganzabal        25
Carlos Castellan          17
Roberto Arguello          13
Fernando Dalla Fontana    11
Gustavo Tiberti           10
Guillermo Aubone          10
Eduardo Bengoechea         5
Gustavo Guerrero           5
Raul Peralta               5
Martin Jaite               5
Alejandro Gattiker         3
Enrique Caviglia           2
Tito Vasquez               2
Roberto Aubone             2
Tomas Lynch                2
Carlos Lando               1
Hugo Varela                1
Carlos Gattiker            1
Jason Van Kerckhoven       1
Gabriel Auroux             1
Name: winner_name, dtype: int64

In [22]:
ochoCuatro["winner_name"].value_counts()[3:].sum()

1136

In [23]:
legion["winner_name"].value_counts()[3:].sum()

1143

In [24]:
davis["winner_name"].value_counts()[3:].sum()

396